name: Build and Deploy to Production Branch

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install and build frontend
      run: |
        cd frontend
        npm ci
        npm run build
        cd ..

    - name: Prepare production branch
      run: |
        # Configurar git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Verificar o crear rama production desde origin
        git fetch origin production:production 2>/dev/null || true
        git checkout -B production
        
        # Limpiar archivos innecesarios
        find . -name "node_modules" -type d -prune -exec rm -rf {} +
        
        # Eliminar archivos de desarrollo del frontend
        rm -rf frontend/src
        rm -rf frontend/public
        rm -f frontend/vite.config.js
        rm -f frontend/eslint.config.js
        rm -f frontend/index.html
        rm -f frontend/README.md
        rm -f frontend/package-lock.json
        
        # Crear archivo de verificación
        echo "Build completed at $(date)" > .build-info
        
        # Agregar todos los archivos necesarios
        git add -f frontend/dist
        git add backend
        git add database
        git add .plesk-deploy.sh
        git add .plesk-deploy-simple.sh
        git add .plesk-test.sh
        git add package.json
        git add .build-info
        git add nginx.conf
        
        # Crear commit
        git commit -m "Production build $(date +%Y%m%d-%H%M%S)" || echo "No changes to commit"

    - name: Push to production branch
      run: |
        git push origin production --force